### ISSUE TITLE
Exclude files from documentation build

### ISSUE THREAD

**Issue by tiagoafpereira** [inductiva/inductiva#1270]
The following warnings are related to two **files that exist in the repository but are not referenced anywhere**:

```
docs/markdown_sample.md: WARNING: document isn't included in any toctree
docs/task_state_diagram.md: WARNING: document isn't included in any toctree
```

_Assuming_ they're still useful we can leave them in the documentation folder but exclude them from the build using this configuration on `conf.py`:

```python
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
        'markdown_sample.md',
        'task_state_diagram.md',
        ]
```

Am I correct in my assumption @sergiomsantos and @IvanPombo ?

**Comment by IvanPombo** [comment]
The `markdown_sample.md` is required for pytest-markdown. The other file I think was needed to generate the task diagram. Either way, I think for now you can add them to the `exclude_patterns` and when not needed anymore we remove them.
