### ISSUE TITLE
`inductiva tasks list` is slow for power users

### ISSUE THREAD

**Issue by rcvalerio** [inductiva/inductiva#1494]
Issue https://github.com/inductiva/tasks/issues/217 did not solve the slow task listing for power users. 

---

User with around 20k tasks.

`inductiva tasks list`  0.33s user 0.06s system 2% cpu 14.589 total

`inductiva tasks list -n 5`  0.34s user 0.06s system 1% cpu 21.209 total

`inductiva tasks list -n 500`  0.38s user 0.05s system 1% cpu 22.968 total

`inductiva tasks list -p windtunnel-dataset` takes roughly 30 minutes (~10k tasks)

`inductiva tasks list -p rvalerio2fb8a80f`  4.74s user 0.24s system 1% cpu 5:41.81 total (4.7k tasks)

--- 
Dev environment with only 50 tasks:

`inductiva tasks list`  0.31s user 0.04s system 41% cpu 0.839 total

`inductiva tasks list -n 5`  0.31s user 0.04s system 42% cpu 0.826 total

`inductiva tasks list -n 50`  0.33s user 0.04s system 39% cpu 0.951 total

**Comment by Pbarbosa92** [comment]
I've done a small improvement in the client's side with this PR https://github.com/inductiva/inductiva/pull/1499

**Comment by Pbarbosa92** [comment]
After some profiling
```
0.10 seconds - inductiva/inductiva/utils/format_utils.py:99 - datetime_formatter
0.38 seconds - inductiva/inductiva/_cli/cmd_tasks/list.py:37 - color_formater
0.68 seconds - inductiva/inductiva/utils/format_utils.py:134 - apply_formatters
0.70 seconds - inductiva/inductiva/utils/format_utils.py:153 - get_tabular_data
4.41 seconds - inductiva/inductiva/utils/format_utils.py:191 - get_tabular_str
1581.69 seconds - inductiva/inductiva/client/paths/tasks/get.py:217 - _get_user_tasks_oapg
1581.69 seconds - inductiva/inductiva/client/paths/tasks/get.py:330 - get_user_tasks
1582.16 seconds - inductiva/inductiva/tasks/methods.py:63 - _fetch_tasks_from_api
1584.77 seconds - inductiva/inductiva/tasks/methods.py:163 - get_all
1584.78 seconds - inductiva/inductiva/projects/project.py:255 - get_tasks
1587.24 seconds - inductiva/inductiva/client/api_client.py:1073 - call_api
1594.59 seconds - inductiva/inductiva/_cli/cmd_tasks/list.py:12 - list_tasks
``` 


![Image](https://github.com/inductiva/inductiva/assets/157368229/fefd3371-25c2-4152-bac4-ec5c9cab2544)

We can see that the slow speed comes from the call to the back end.

**Comment by bgregoinductiva** [comment]
There should be some improvement after these PRs:
- https://github.com/inductiva/inductiva-web-api/pull/990
- https://github.com/inductiva/inductiva/pull/1499

More work needs to be done in the scope of this issue:
- https://github.com/inductiva/inductiva-web-api/issues/1014

**Comment by Pbarbosa92** [comment]
@rcvalerio can you re-test this just to check if it is fixed.

**Comment by rcvalerio** [comment]
It is much faster:

$ time inductiva tasks list --all
real    0m44,795s
user    0m2,943s
sys     0m0,360s

**Comment by Pbarbosa92** [comment]
@hpenedones do you consider this time to be acceptable?

**Comment by hpenedones** [comment]
Yes, I think that for now it's perfectly acceptable -- we went from about 20mins to 45 seconds. It's not too shocking that listing 20k + tasks could take that long, at least for now. If in the future we would notice that users (or ourselves) would often run tasks list --all in their data processing pipelines and this was becoming a bottleneck, we could try to optimize it even further. Great work on the profiling you did back in June, @Pbarbosa92 !
