### ISSUE TITLE
Replace animations shown in Jupyter Notebooks by matplotlib animations

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#158]
ATM we use `imageio` to produce videos from frames. This is causing some issues in notebooks, like poorly rendered movies...

I came across [matplotlib animations](https://matplotlib.org/stable/api/animation_api.html), which allow a movie to be created out of a sequence of frames built with simple functions and have handy methods such as `to_html5_video` and `to_jshtml`. These seem to render nicely in Google Colab, and `to_jshtml` even has built-in play/pause/forward/etc buttons to control the video play.

See this [example Google Colab](https://colab.research.google.com/drive/11Fpu-7uWeSdmGFYzBYu9eYCZKQteUNuM?usp=sharing).

WDYT?

**Comment by IvanPombo** [comment]
This issue seems to be out of place with our current paradigm. Gonna close it as not planned, add it to a visualisations document and eventually we can open it up if we decide to follow on this.
