### ISSUE TITLE
Study the possibility of adding Altair's OpenRadioss to the API

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#225]
https://www.openradioss.org/

**Comment by sarmento** [comment]
@Joao97ribeiro @baribeiro can you please have a look at this too?

**Comment by Joao97ribeiro** [comment]
> @Joao97ribeiro @baribeiro can you please have a look at this too?

This software seems interesting. They have a tutorial for a well-known case in mechanical engineering, the Tensile Test: https://openradioss.atlassian.net/wiki/spaces/OPENRADIOSS/pages/24444938/Tensile+Test+Example+Tutorial+Using+Gmsh. 

They also have provided a guide on how to run OpenRadioss here: https://openradioss.atlassian.net/wiki/spaces/OPENRADIOSS/pages/19628079/Running+OpenRadioss."
