### ISSUE TITLE
Ability to run simulations Async

### ISSUE THREAD

**Issue by IvanPombo** [inductiva/inductiva#230]
We have been discussing this aspect for a while, and finally there was a user request for it: "Is it possible to receive the results even if my PC is off...". Therefore, I think it is time to start implementing it.

The priority for now seems to be for the low-level simulation calls and from what I have been discussing with @luispcunha it will take a bit more extra work for the scenarios. Since the low-level calls are the backbone of the scenarios, we can start by implementing an async method for them. Moreover, we can provide the option to run sync and async simulations.

The steps:
- [x] Add personal tokens and simulation identification tokens on the server side. This will allow users to check their job list, statistics and identify the simulations they may want to download to their side.
- [x] Implement methods to send a simulation and to fetch a simulation via simulation identification token. The idea is to split the invoke api functions into smaller steps. There is already various functions to manage tasks that will allow to treat this with simplicity.
- [x] Implement methods for users to check their job list. In the near future, this can also include statistics of time and hardware used, which is good for both parties.
- [x] Maybe, by default, the current invoke_api method should be able to keep running a simulation in case we do not cancel it, but there is some event that causes the collapse of the computer or IDE. For example, a simple event is internet connection drop.
- [ ] Attach a simulation that is still running to check the simulation logs. This goes in hand with the item above or with the idea of just checking in if everything is ok, and detaching again. The idea is very similar to the `screen` method on terminal, but we are providing this feature in the client side.

There might still be intermediate steps in each of the ones above. This issue serves to open the discussion and implementation, since users are already asking for it. Feel free to split each task into more focused issues.

**Comment by fabiocruz** [comment]
Possibly related to #81.
