### ISSUE TITLE
Add basic syntax checks to functions that read commands from files

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#308]
It should also do some kind of verification that the loaded content is compatible with our definition of commands, e.g. check that it reads a list of dicts with the desired keys.

_Originally posted by @fabiocruz in https://github.com/inductiva/inductiva/pull/305#discussion_r1243802519_

**Comment by IvanPombo** [comment]
Closing since the commands are now checked for syntax in each executer.
