### ISSUE TITLE
[Heat sink scenario] Add support for a parametric heat sink

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#332]
The heat sink currently in the scenario has fixed dimensions, number of fins, etc. We could allow for a parametric heat sink, generate the corresponding meshes on the fly with gmsh and simulate them. This would allow nice comparative studies between standard heat sinks.

**Comment by IvanPombo** [comment]
This is much more high-level than we are ready to have. Users should just be able to insert their own shape for now and in the future we can see if it makes sense this parametrization.
