### ISSUE TITLE
[Feature] Possibility to download  a single file from the output dir instead of the whole output_directory

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#341]
**Context:** 
The output directory of a GROMACS simulation is big. Doing a simulation of a small protein for 100 ns results in a output with 5Gb. The biggest file is the precise trajecory file, with about 4.9 GB. To produce the visualization, I just need the  compressed trajectory file which is just some Mb. 
At this moment, the `inductiva.tasks.fetch_task_output()` method downloads the full output_directory as a zip file. 
**Possible solution 1:** 
Upload to blob storage just the compressed trajectory file and erase the other auxiliary files. 
Con: expert users may want to access other files to analyse, debug and produce more visualisations. 
**Possible solution 2:** 
Introduce two different methods:
`inductiva.tasks.fetch_task_output_folder()` where the folder is downloaded in its totality. 
 `inductiva.tasks.fetch_task_output_file()` where only a specific file is downloaded. This could then be used in the scenarios to download just the specific file with the method `scenario.download_output()`.
Cons: To implement the download of a specific file, I don't think we can have the output in a zip file in the blob storage, to be able to access the specific location in the blob storage. 

What do you think the best solution is?

**Comment by luispcunha** [comment]
The "con" you present for solution 2 isn't fully correct, because the files in a ZIP are compressed individually, we don't need to extract the full contents of the ZIP to access a single file. Check this: https://docs.python.org/3/library/zipfile.html, we can extract a single file from a ZIP.

**Comment by cristianacarpinteiro** [comment]
Thanks for the suggestion @luispcunha, I will work on implementing this :)

**Comment by cristianacarpinteiro** [comment]
solved in https://github.com/inductiva/inductiva-web-api/pull/213.
