### ISSUE TITLE
[Launch machines] Refactor method and create a Machines object

### ISSUE THREAD

**Issue by begaiym-k** [inductiva/inductiva#354]
- Simplify the existing script, ex: inductiva.resources.launch_machine_group().
- Create a class object that will have terminate(), start(), estimate_cost() methods.
- Pass that object to every simulate/run methods available.

**Comment by david451lima** [comment]
Example code that we want the user to write:

```
machine_group = inductiva.resources.create_machine_group(
    machine_type="c2-standard-4",
    spot=True,
    num_machines=1,
)

machine_group.estimate_cost()
machine_group.start()
machine_group.terminate()
```

**Comment by IvanPombo** [comment]
I had this idea to integrate a name in the machine group that associates it with a project (ours or the user project). In this way, the user can query the cost and resources consumed for that specific project (time and cost).
