### ISSUE TITLE
Create task class

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#355]

**Comment by david451lima** [comment]
Create a Task class, that is the return of simulate_async methods and has the ability of killing tasks and checking its status
```
task = cenario.simulate_async(simulation_time = 0.002,  machine_group = machine_group)
task.status()
task.kill()
```

**Comment by sarmento** [comment]
Quick note on this just to think about: to enforce consistency, should we only have one method, called simulate(). If we want it to run asynchronously, then we pass a parameter async=True. This approach will make sure we consistently process both cases.

**Comment by luispcunha** [comment]
> Quick note on this just to think about: to enforce consistency, should we only have one method, called simulate(). If we want it to run asynchronously, then we pass a parameter async=True. This approach will make sure we consistently process both cases.

That is being discussed in #362.
