### ISSUE TITLE
Merge `simulate` and `simulate_async`?

### ISSUE THREAD

**Issue by IvanPombo** [inductiva/inductiva#362]
Following the issues #355 and #356, we could easily merge the `simulate` and `simulate_async` methods into one by using the task object output. In general, both methods are relatively the same, with the exception that we are "logging" and holding in the sync. 

The main reason we had not done it before, was due to a difference in inputs (namely, we did not have `output_dir` for the async) and a difference in outputs (`output_dir` and `task_id`).  With a task object, we could immediately have everything concerning a task, including an attribute for the output path. When doing `task.download()` it would be immediate to that output. Furthermore, adding the task info 

The only problem is that we would discard obtaining the visuals object at the end of `simulate` method. 

Wdyt?

**Comment by fabiocruz** [comment]
I think the plan is for `simulate` to return an output object and `simulate_async` to return a task object, so I don't see how these can be merged (based on the argument that inputs and outputs should be the same).

Returning a task object in `simulate` would require importing the output class in each scenario, e.g.
```python
from inductiva... import DamBreak
from inductiva... import DamBreakOutput

scenario = DamBreak(...)
task = scenario.simulate(...)
task.downlaod_output()
output = DamBreakOutput("output_dir")
```

**Comment by IvanPombo** [comment]
> I think the plan is for `simulate` to return an output object and `simulate_async` to return a task object, so I don't see how these can be merged (based on the argument that inputs and outputs should be the same).
> 
> Returning a task object in `simulate` would require importing the output class in each scenario, e.g.
> 
> ```python
> from inductiva... import DamBreak
> from inductiva... import DamBreakOutput
> 
> scenario = DamBreak(...)
> task = scenario.simulate(...)
> task.downlaod_output()
> output = DamBreakOutput("output_dir")
> ```

You would not need to download the output, the simulate would do it. However, I agree with the import of the output class. 

Notice that most meaningful simulations will need the async method anyway, so the usual workflow will be to always import the output anyway.

**Comment by fabiocruz** [comment]
> You would not need to download the output, the simulate would do it.

You're right!

> Notice that most meaningful simulations will need the async method anyway, so the usual workflow will be to always import the output anyway.

Good point. I'm ok with importing the output.

I am also ok with merging the methods, as long as it is still explicit that we are running sync/async simulations. Were you thinking of adding a parameter `async=True|False` to `simulate`?

**Comment by cristianacarpinteiro** [comment]
I like the idea parameter async=True|False! That's what I thought too. 

Regarding this example, I have some comments: 

```
from inductiva... import DamBreak
from inductiva... import DamBreakOutput

scenario = DamBreak(...)
task = scenario.simulate(...)
task.downlaod_output()
output = DamBreakOutput("output_dir")
```
For gromacs I just want to download two specific files (there are some heavy files that are not necessary for the visualization), and I thought that I would define this inside the scenario.simulate and the simulationOutuput would work with just the downloaded files. Having the simulate return the task would mean that I would have to do.

```
scenario = ProteinSovation(...)
task = scenario.simulate(...)
task.downlaod_output_files(files=["trajectory.xtc", "protein.pdb"])
output = GromacsOutput("output_dir")
```

Having to define the filenames by the user doesn't take out the "magic" of the user experience?

**Comment by fabiocruz** [comment]
> Having to define the filenames by the user doesn't take out the "magic" of the user experience?

I don't think it does. I'd say this is an intermediate/advanced feature that intermediate/advanced users may find useful, so the effort of listing file names pays off!

**Comment by IvanPombo** [comment]
> I like the idea parameter async=True|False! That's what I thought too.
> 
> Regarding this example, I have some comments:
> 
> ```
> from inductiva... import DamBreak
> from inductiva... import DamBreakOutput
> 
> scenario = DamBreak(...)
> task = scenario.simulate(...)
> task.downlaod_output()
> output = DamBreakOutput("output_dir")
> ```
> 
> For gromacs I just want to download two specific files (there are some heavy files that are not necessary for the visualization), and I thought that I would define this inside the scenario.simulate and the simulationOutuput would work with just the downloaded files. Having the simulate return the task would mean that I would have to do:
> 
> ```
> scenario = ProteinSovation(...)
> task = scenario.simulate(...)
> task.downlaod_output_files(files=["trajectory.xtc", "protein.pdb"])
> output = GromacsOutput("output_dir")
> ```
> 
> Having to define the filenames by the user doesn't take out the "magic" of the user experience?

Again, remark that you want have to perform the download_output_files with the simulate sync, this step will keep being automatic since it is done in the backend. I agree with Fabio, this is an advanced feature that users and us will find very useful. I will add a comment on the specific issue for those files, since I still want to understand this feature.

**Comment by hpenedones** [comment]
Thanks for this Ivan, a few comments:

In both sync and async:

- Why do we need a `output_dir="output_folder"` for a scenario?
It shouldn't be needed if we are returning a scenario output object, right? If the user wants to download the whole file outputs, that would be done later, with the method downlaod_output_files("output_dir")


 In the async version, it does not make sense to ask the user to explicetely construct the scenario output based on an output folder, that is too low level.

I will edit the colab to specify what I think is a clean interface.

**Comment by hpenedones** [comment]
<img width="715" alt="image" src="https://github.com/inductiva/inductiva/assets/1058075/e4e50c67-2187-493c-b390-26c3b733ce7f">

**Comment by IvanPombo** [comment]
> <img alt="image" width="715" src="https://user-images.githubusercontent.com/1058075/254943597-e4e50c67-2187-493c-b390-26c3b733ce7f.png">

In this manner, you would have two different types of outputs depending on if the simulation is sync or async. That was the motive we had to choose the split.

**Comment by IvanPombo** [comment]
> Thanks for this Ivan, a few comments:
> 
> In both sync and async:
> 
> * Why do we need a `output_dir="output_folder"` for a scenario?
>   It shouldn't be needed if we are returning a scenario output object, right? If the user wants to download the whole file outputs, that would be done later, with the method downlaod_output_files("output_dir")
> 
> In the async version, it does not make sense to ask the user to explicetely construct the scenario output based on an output folder, that is too low level.
> 
> I will edit the colab to specify what I think is a clean interface.

The scenario output object needs the files downloaded to run. Would you suggest downloading only the specific files for each output function or assume the default? Currently, it can work without passing any output_dir, it is not obligatory, but users actually know in this way the folder where it went.

I like your suggestion to use `output=task.get_output` and move from there! 

I understand your workflow and fits perfectly with what I had in mind! I will implement it!

**Comment by hpenedones** [comment]
> 

See the example of Ray and their remote tasks:
https://docs.ray.io/en/latest/ray-core/walkthrough.html#running-a-task

When you annotate a function to run remotely (async), it no longer returns the original type, but it returns a task_id that allows you to do ray.get(task_id) which will return whatever was the original type returned by the function.  The goal is todo something similar, but we can chose to return a task object instead of a task_id, and instead of doing inductiva.get(task_id) we can do task.get_output()...

Whether we have two functions simulate, and simulate_async, or one function simulate with an argument async=True, is not such a big issue, I am ok with both, the important is that when you run async, you only need to do a very simple blocking call to get back the results, and you should be EXACTLY in the same situation as with the blocking call. The problem with the code you were suggesting, is that it required the user to talk about downloading files, to some directory, and then it needed to known which constructor to call (like WindTunnelOutput or something) to get back the output. That can not happen....

**Comment by fabiocruz** [comment]
Thank you @hpenedones for the feedback.

> * Why do we need a `output_dir="output_folder"` for a scenario?

We need it for a scenario's `simulate` method to be able to control where output files are written to, since so far we have been assuming that simulations run synchronously get their output downloaded at completion.
