### ISSUE TITLE
Add wall in dam break scenario

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#37]
Currently we have:

```python

scenario = fluids.scenarios.DamBreak(fluid=fluids.WATER,
                                     fluid_dimensions=(.2, 1, 1),
                                     fluid_position=[0.0, 0.0, 0.0],
                                     resolution="medium",
                                     time_max=2)

sim_output = scenario.simulate()


```
which generates a simulation inside a box, unrestricted. Now we want to add a wall so that we block part of the fluid. We will start with a simple rectangular wall, where we define only the width and the height of the wall, and position from the bottom of the simulation box. 

```python
scenario = ....

scenario.add_rectangular_wall(height=0.3, width=0.05, distance_to_back=0.1)

sim_output = scenario.simulate()
```

This is a first step to creating more sophisticated walls, either by having different type of walls, or by defining a profile for extrusion (e.g. a line in .obj).

**Comment by IvanPombo** [comment]
This seems to just be a toy model for now and as we moved to better scenarios, it seems to be irrelevant. The issue of adding a breakwater to the coastal area is more important and addresses better what we want to achieve with this.
