### ISSUE TITLE
Infinite height in dam break scenario

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#38]
Currently, the Dam Break scenario seems to have a maximum height, so particles easily hit the ceiling. This introduces an unwanted distortion to the scenario that we don't need to have, and it raises questions from the point of view of the user that we want to avoid. Change the height of the simulation box to a value that is much higher, while still only showing in the simulation only a region that is just 1 to 1.5 the "standard" height.

**Comment by IvanPombo** [comment]
This issue seems to be irrelevant at the moment as we moved to more realistic scenarios to show case the API. Gonna close with not planned and in case it is still relevant we can open it again.
