### ISSUE TITLE
[Task Class] Create price and time atributes

### ISSUE THREAD

**Issue by david451lima** [inductiva/inductiva#385]
Create two new atributes for the task class:

- ```task.time``` that gives the time that the simulation took to run (task.end_time - task.start_time. The unit in which this is  displayed is in seconds;
- ``` task.price = xxxx ``` that gives the price of the simulation (task.time * 'price of the machine in which the simulation ran').

**Comment by IvanPombo** [comment]
Closing this, since it was already open in another issue management.
