### ISSUE TITLE
Support render of MD simulations outside jupyter notebook

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#395]
I believe this won't be the right solution to move forward, since it is not super clean and not adaptable to under editors.
However, I think it provides the visuals now for the scenario, but I would keep this an high priority to change this in the near future.

_Originally posted by @IvanPombo in https://github.com/inductiva/inductiva/pull/376#pullrequestreview-1545869433_

**Comment by IvanPombo** [comment]
This is connect with other more recent issues like #616 and #614. So I am gonna close this and any discussion should be contained to those places.
