### ISSUE TITLE
Restructure SimulationOutput

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#475]
Thank you for this work.
I don't have a lot of context so my general comment is that we may need a bit more documentation to allow for other people to help you reviewing the code, otherwise you get stuck and nobody can really help you. Please help the others help you :)

My biggest concern is that is seems that the  ProteinSolvationOutput class is trying to provide too many functionalities: everything from visualization to doing some post-processing analysis is hanging from this class. In many cases, these methods almost don't use any information from the object except maybe one field, and then they do their things with several steps not involving the information of the object. I think ProteinSolvationOutput should be simpler and then passed as input to methods that do more complicated stuff (e.g. compute RMS or other interesting things.)

Anyway, I think we need one more round of cleaning up. There are still a number of little things that can be improved, besides what I believe is a major refactoring that may need to be done later.

_Originally posted by @sarmento in https://github.com/inductiva/inductiva/pull/464#pullrequestreview-1573992315_

**Comment by IvanPombo** [comment]
Closing this, since we are moving this class out with the respective scenario.
