### ISSUE TITLE
[Coastal area scenario] Add ability to load bathymetry from standard file format

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#478]
The following describes the problem with the current implementation of the coastal area scenario and the associated bathymetry class, as well as a tentative solution to solve this problem. I would like to collect feedback on this proposal before implementing anything. Thanks!

## Problem

The current implementation of the coastal area scenario requires that the user loads a text file with a grid of depth values defining the bathymetry to be used in the simulation.

While this in theory allows the user to use different bathymetries in simulations, it is not practical, since bathymetry data from *standard* sources / file formats cannot be used.

The main challenge in a user workflow thus seems to be loading standard bathymetry data and converting it to a format that can be consumed by simulators such as SWASH and XBeach.

The challenges of loading standard bathymetry data are:
1. There is no single *standard* source / file format. There are centralized repositories for this data, e.g. [European Marine Observation and Data Network  (EMODnet)](https://emodnet.ec.europa.eu/geoviewer/#!/), which follows an European policy and thus has some level of control over the format in which bathymetry data is stored. 
2. Bathymetry data is usually collected at a sample of locations that are not necessarily a) uniformly distributed in space, b) labeled with cartesian coordinates instead of latitude, longitude pairs, etc., as required by SWASH.

## Tentative solution

Ideally, we would be able to load bathymetries, inspect them and pre-process them before they can be passed to a simulator.

### File format

I suggest we start by adding support to bathymetries provided in the ASCII XYZ format defined [here](https://emodnet.ec.europa.eu/sites/emodnet.ec.europa.eu/files/public/20171127_DTM_exchange_format_specification_v1.6.pdf). This is a format provided in many of the datasets in EMODnet, see e.g. [this data from Algarve](https://sextant.ifremer.fr/record/SDN_CPRD_590_HR_Lidar_Algarve/).

### Bathymetry class

Due to the different definition of the bathymetry data in typical sources (scattered vs grid values, etc.), our `Bathymetry` class needs to be updated.

I suggest we allow loading a bathymetry with "no further questions asked", i.e.
```python
bathymetry = inductiva.....Bathymetry.from_ascii_xyz_file(file_path)
```

The `Bathymety` class should:
1. Store information as read from the file, i.e. a list of coordinates and corresponding depths, and not arbitrarily crop it/interpolate it to a grid.
2. Contain a visualization method that allows inspecting the loaded bathymetry.
3. Contain a cropping method that allows selecting only sub-regions.
4. Contain a method to interpolate data to a grid. The scenario class `CoastalArea` should inspect that the provided bathymetry is indeed defined on a grid.

### User workflow

A typical user workflow should thus be:

1. Load the bathymetry

```python
> bathymetry = inductiva.....Bathymetry.from_ascii_xyz_file(file_path)
```

2. Plot the bathymetry

```python
> bathymetry.plot()
```

This should return a plot of the raw bathymetry, e.g. for the Algarve data mentioned above this would be similar to

![bathymetry](https://github.com/inductiva/inductiva/assets/11545632/03ff6fb6-052e-4211-9d57-f270b3852412)

3. Crop the bathymetry

```python
> bathymetry = bathymetry.crop(x_range=[562000, 563000], y_range=[4102600, 4103500])
> bathymetry.plot()
```

![bathymetry_crop](https://github.com/inductiva/inductiva/assets/11545632/dfd89c7f-7481-4523-9aa2-205c7a8fc5bf)

4. Interpolate the bathymetry to a grid

```python
> bathymetry = bathymetry.interpolate_to_grid(x_num=200, y_num=200)
> bathymetry.plot_grid() # or other name?
```

![bathymetry_grid](https://github.com/inductiva/inductiva/assets/11545632/0c0d3802-725c-428d-b3ad-c78fa0358aa5)

5. Simulate

```python
> scenario = inductiva.....CoastalArea(bathymetry=bathymetry, ...)
> task = scenario.simulate()
```

6. Render simulation outputs

```python
> output = task.get_output()
> output.render()
```

https://github.com/inductiva/inductiva/assets/11545632/62f67e7c-2928-4fc4-9060-2fb393ba627c

**Comment by cristianacarpinteiro** [comment]
Thanks @fabiocruz for the detailed description. I think that this makes a lot of sense! Just one comment: 
Why have both the `bathymetry.plot_grid()` and `bathymetry.plot()` method? Why not have just the `bathymetry.plot()` plot the grid directly. This seems like the most intuitive visualization for me. Am I missing something?

**Comment by hpenedones** [comment]
Cool, thanks Fábio, this seems reasonable overall. Related with @cristianacarpinteiro question/suggestion, which makes sense: before doing the simulation does the user necessarily have to call the `interpolate_to_grid` method? What happens if the user does not do that and passes a bathymetry that is not a regular grid? Were you planning to throw some error, or doing some interpolation with default values "automagically"?

**Comment by fabiocruz** [comment]
> Thanks @fabiocruz for the detailed description. I think that this makes a lot of sense! Just one comment: Why have both the `bathymetry.plot_grid()` and `bathymetry.plot()` method? Why not have just the `bathymetry.plot()` plot the grid directly. This seems like the most intuitive visualization for me. Am I missing something?

You're right. We should provide a single method to visualize bathymetries, regardless of them representing data in a uniform grid or not. I'll test [`matplotlib.pyplot.pcolormesh`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pcolormesh.html) instead.
