### ISSUE TITLE
[Coastal area scenario] Add breakwater to a bathymetry

### ISSUE THREAD

**Issue by fabiocruz** [inductiva/inductiva#520]
One of our API users wants to be able to add a breakwater structure to a bathymetry, more specifically vertical breakwaters (think of a parallelepiped going from the sea bottom to some elevation above the sea level).

Below I propose an interface to do so, for which I'd appreciate to receive some feedback before implementing it.

## Breakwater class

I suggest adding a `Breakwater` class, which would be initialized as follows:

```python
breakwater = inductiva.fluids.scenarios.coastal_area.Breakwater(
    x_center=..., # The x coordinate of the center of the breakwater.
    y_center=...,
    x_length=..., # The length of the breakwater along the x axis.
    y_length=...,
    rotation_angle=..., # The angle to rotate the breakwater relative to the positive direction of the x axis.
    crest_elevation=..., # How above the sea level the breakwater extends.
)
```

NB: the parameters describing the breakwater have been discussed with the user, and seem to provide a sufficient description of these structures.

## Bathymetries with breakwaters

I suggest supporting adding breakwaters to bathymetries.

When initializing a bathymetry from the class constructor, one could pass a list of breakwaters:
```python
bathymetry = inductiva.fluids.scenarios.coastal_area.Bathymetry(
    x=...,
    y=...,
    depths=...,
    breakwaters=[breakwater,],
)
```

When initializing a bathymetry from the available classmethods to read data from files (e.g. ASCII XYZ files), I don't think it makes much sense to support adding bathymetries on initialization.

I suggest instead that we have a method to add breakwaters to bathymetries:

```python
bathymetry = inductiva.fluids.scenarios.coastal_area.Bathymetry.from_ascii_xyz_file(...)
bathymetry.add_breakwaters([breakwater,] # -> None
```

When a bathymetry has a breakwater (or more than one), the depth in the region of the breakwater is overridden by the crest elevation of the breakwater.

Allowing adding breakwaters to bathymetries in this manner allows users to e.g. load arbitrary bathymetry files, add breakwater structures to them and export new bathymetry files to be used as they please (e.g. to run simulations).

**Comment by IvanPombo** [comment]
This seems great @fabiocruz!!

**Comment by hpenedones** [comment]
@sarmento and I were chatting about the right interface for this scenario, and he suggested having something like:

`bathymetry = inductiva.coastal.scenarios.Bathymetry(...)`

(instead of fluids, and  the longer class names.)
This would bring the coastal scenarios to a more "prime" location and simplify the code. What do you think?

**Comment by fabiocruz** [comment]
> @sarmento and I were chatting about the right interface for this scenario, and he suggested having something like:
> 
> `bathymetry = inductiva.coastal.scenarios.Bathymetry(...)`
> 
> (instead of fluids, and the longer class names.) This would bring the coastal scenarios to a more "prime" location and simplify the code. What do you think?

Sounds good, I can update the structure to follow your suggestion. I don't think `Bathymetry` should be under a `scenarios` submodule though, since it does not represent a scenario. It could be instead simply under `inductiva.coastal`.

What do you think specifically about the breakwater interface suggested here?

**Comment by hpenedones** [comment]
Yes, I was just writing that as wel... In theory, one could even have the Bathymetry and Breakwater classes one level up:

```
bathymetry = inductiva.coastal.Bathymetry(...)
bathymetry = inductiva.coastal.Breakwater(...)
```

Not sure what would be best, wdyt?

**Comment by fabiocruz** [comment]
That sounds better, yes!

**Comment by hpenedones** [comment]
Regarding the Breakwater interface, I think it's reasonable, but a couple of things might create confusion:

1) the user will specify `x_length` and `y_length`, which initially seems fine, but then there is a `rotation_angle`, which means that those values will no longer be the values along x or y axis. Therefore, it would probably be more natural to ask for: `length`, `width` (and `crest_elevation`), to define the Breakwater. 

2) The parameters `x_center`, `y_center` could be thought of parameters of where to put the breakwater into the scenario... Here he have two choices: 1) you do it right away when you create the Breakwater like you did, or 2) you do it when you pass the breakwater to the bathymetry, and say something like `bathymetry.add_breakwater(breakwater, x_center, y_center, rotation_angle)`

Something like that, wdyt?

**Comment by fabiocruz** [comment]
> 1. the user will specify `x_length` and `y_length`, which initially seems fine, but then there is a `rotation_angle`, which means that those values will no longer be the values along x or y axis. Therefore, it would probably be more natural to ask for: `length`, `width` (and `crest_elevation`), to define the Breakwater.

I thought about this... how would you define what is the length and what is the width? Since these can be placed in arbitrary bathymetries (where a beach/harbour can "stretch along" the x or y axes), I was having a hard time picking which should correspond to their size along x or y.

> 2. The parameters `x_center`, `y_center` could be thought of parameters of where to put the breakwater into the scenario... Here he have two choices: 1) you do it right away when you create the Breakwater like you did, or 2) you do it when you pass the breakwater to the bathymetry, and say something like `bathymetry.add_breakwater(breakwater, x_center, y_center, rotation_angle)`

Good point. It makes sense that `x_center`, `y_center` and `rotation_angle` are attributes of the bathymetry, which define where each breakwater should be placed.  Then the same breakwater could be reused in different bathymetries, or in different positions in the same bathymetry. I'll move forward with this in mind.

Thanks for the feedback.

**Comment by IvanPombo** [comment]
Closing this, since it is not planned to move forward.
