### ISSUE TITLE
[CoastalArea] Confusing / Unexpected messages in coastal scenario

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#583]
I was preparing a simpler example for the tutorial (one that does not require downloading any file), so I running this code:

```
print("Generating Random Bathymetry")
bathymetry = inductiva.coastal.Bathymetry.from_random_depths(
        x_range=(0, 1000),
        y_range=(0, 1000),
        x_num=200,
        y_num=200,
        max_depth=10)

print("Plotting")
bathymetry.plot()

print("Creating Scenario")
scenario = inductiva.coastal.CoastalArea(bathymetry=bathymetry,
                                         wave_source_location="W",
                                         wave_amplitude=5,
                                         wave_period=5.5)

print("Calling Simulate")
task = scenario.simulate(simulation_time=100, output_time_step=1)

output = task.get_output()

output.render()
```

And got these messages on the terminal

```
Generating Random Bathymetry
INFO:absl:Generating random array with the Diamond-Square Algorithm...
Plotting
INFO:absl:Plotting the bathymetry on a uniform grid...
INFO:absl:Interpolating the bathymetry to a uniform grid...
- grid resolution 10.000000 x 10.000000 (m x m) 
- grid size 100 x 100
Creating Scenario
Calling Simulate
INFO:absl:Interpolating the bathymetry to a uniform grid...
- grid resolution 5.000000 x 5.000000 (m x m) 
- grid size 200 x 200
```

Here's a few confusing things that I think we need to change for this release:

1) Since I generated a random bathymetry with those parameters/arguments, I was expecting it to be a uniform grid bathymetry already (the parameters suggest that). Why would we need to interpolate it before plotting? 

2) I am calling plot with no parameters. The default behaviour should be plotting the bathymetry whatever "resolution" it has. In this case, we explicitly set it to have 200 x 200, so there is really no need to "scale it down" to 100x100.

3) When calling simulate, why are we interpolating again back to the original size? Are we upsampling again after downsampling it? What is happening here? If we are actually not interpolating, these massages are a bit confusing an unexpected.

This *needs* to be fixed for this release, since I want to send this example to a number of people.

**Comment by IvanPombo** [comment]
After running some tests with this scenario as well, and noticing the script above, I am not sure if I understand what `x_range` and `y_range` variables are. We are setting `x_range=[0, 1000]` so the bathymetry should have 1000m of length in the x-direction. The code documentation also states that this is in meters...

However, in the below messages it refers that the grid resolution is 10 x 10 (m x m), which does not make a lot of sense. Can you verify if we are passing a 10x10 grid to the simulation or if it is just the message that is incorrect.

**Comment by sarmento** [comment]
I want to create a bathymetry with 200 x 200 meters.
I want to have a grid with 50x50 points (4m resolution).

this is the code:

```
print("Generating Random Bathymetry")
bathymetry = inductiva.coastal.Bathymetry.from_random_depths(
        x_range=(0, 200),
        y_range=(0, 200),
        x_num=50,
        y_num=50,
        max_depth=10)

print("Plotting")
bathymetry.plot()



print("Creating Scenario")
scenario = inductiva.coastal.CoastalArea(bathymetry=bathymetry,
                                         wave_source_location="W",
                                         wave_amplitude=5,
                                         wave_period=5.5)

print("Calling Simulate")
task = scenario.simulate(simulation_time=100, output_time_step=1)

output = task.get_output()

output.render()


```


Am I missing something?


```
Generating Random Bathymetry
INFO:absl:Generating random array with the Diamond-Square Algorithm...
Plotting
INFO:absl:Plotting the bathymetry on a uniform grid...
INFO:absl:Interpolating the bathymetry to a uniform grid...
- grid resolution 10.000000 x 10.000000 (m x m) 
- grid size 20 x 20
Creating Scenario
Calling Simulate
INFO:absl:Interpolating the bathymetry to a uniform grid...
- grid resolution 4.000000 x 4.000000 (m x m) 
- grid size 50 x 50
INFO:absl:Task ID: 1694691167111786073
INFO:absl:Creating input archive...
INFO:absl:Input archive created.
INFO:absl:Input archive size: 28.06 KiB
INFO:absl:Uploading input...
INFO:absl:Input archive uploaded.
INFO:absl:Task request submitted.
INFO:absl:Waiting for resources...
INFO:absl:The task is being executed remotely.
```

**Comment by IvanPombo** [comment]
Okay, I think now I understand the grid resolution and grid size... The first interpolation is what is getting really confusing...

**Comment by sarmento** [comment]
There should be no interpolation at any moment. 
A random bathymetry is already a grid. I don't want that size to change.
Plotting should also not interpolate if I am not asking the image to be of a different size.
There is NO need for any interpoloation.

**Comment by IvanPombo** [comment]
> There should be no interpolation at any moment. A random bathymetry is already a grid. I don't want that size to change. Plotting should also not interpolate if I am not asking the image to be of a different size. There is NO need for any interpoloation.

There needs to be interpolation for grids that are not uniform. However, if it is already uniform than it should be fixed. On the plotting I agree!

**Comment by sarmento** [comment]
Yes: but the random bathymetry is already uniform.

**Comment by IvanPombo** [comment]
> Yes: but the random bathymetry is already uniform.

Indeed... my apologies for this confusion - I thought Fábio had random generation for general grids at some point...

**Comment by sarmento** [comment]
Thanks for solving this!
