### ISSUE TITLE
[CoastalArea] Image does not open by running this from terminal

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#584]
Running this code from the terminal:

```
print("Generating Random Bathymetry")
bathymetry = inductiva.coastal.Bathymetry.from_random_depths(
        x_range=(0, 1000),
        y_range=(0, 1000),
        x_num=200,
        y_num=200,
        max_depth=10)

print("Plotting")
bathymetry.plot()
```

Does not actually show an image.

**Comment by sarmento** [comment]
According to Fabio:

"
4) In fact, there was no window popping up with the plots. There was also no figure being saved to file.

This was done on purpose. When the plot method is called without setting the output file path, then the method returns a matplotlib axis object. This is the common pattern in libraries that support plotting using third-party plotting packages, see e.g. pandas.DataFrame.plot or yt's ProjectionPlot. This has a number of purposes: a) allow the code to be run without depending on virtual displays, b) allow the user to further configure the figure/axis after plotting the data, c) allow the figure/axis object to be represented as defined by the plotting library authors — in matplotlib’s case, an axis is rendered when attempted to represent in html (e.g. when running the code in jupyter notebooks).
"

@david451lima: please change the example in the readme to run on the terminal *and show the image*. Remember that the default/shortest path is running things in terminal (simplest possible way) not on Jupyter notebooks, colabs. etc...

**Comment by sarmento** [comment]
Hi!
Any news on this?
Questions:

a) Should we change the behavior of plot()? 
b) Should plot return something that we can then manipulate? (and we change the example)
c) Should plot get an extra argument?
d) Should plot be smarter in a way than "understands" the environment?

As a user, I can't really test the example if I can't check the random bathymetry from my terminal (Mac).

**Comment by sarmento** [comment]
Great. It works! :)
The example needs to be updated.
After fixing the docs we can close this issue.
Thanks!

**Comment by david451lima** [comment]
The docs are updated with the examples that run both in terminal and in notebook.
