### ISSUE TITLE
Simulator Naming Convention

### ISSUE THREAD

**Issue by IvanPombo** [inductiva/inductiva#597]
Just to clean up the rest of the package with a consistent approach:

Following the guidelines, our current simulators should be named as:
- SplishSplash
- GROMACS
- OpenFOAM
- DualSPHysics
- Fenicsx
- SWASH
- Xbeach
- Simsopt

**Comment by hpenedones** [comment]
I think it looks good, perhaps with the exception of XBeach (instead of Xbeach), because X is some capital letter they use as a prefix and then Beach is a word. Again "luckily" in this case it also coincides with what they use officially.

**Comment by luispcunha** [comment]
If I followed the guidelines, I would've arrived at SIMSOPT instead of Simsopt, as it seems to be an acronym for Simons Stellarator Optimizer, at least according to their [github](https://github.com/hiddenSymmetries/simsopt).

**Comment by hpenedones** [comment]
This simulator names are stretching the python guidelines to the limits! LOL For simsopt they never use the capitalised version anywhere in their website, so they don't quite treat it as an acronym, but I agree that this is one seems yet another level of gray area. Let's keep it like this for now. I will send an email to the team regarding the process to make these decisions.

**Comment by luispcunha** [comment]
They seem to use it: https://joss.theoj.org/papers/10.21105/joss.03525

**Comment by hpenedones** [comment]
Oh, ok, good catch, so then it becomes more clear.
