### ISSUE TITLE
[CAD Object] Module Design 

### ISSUE THREAD

**Issue by IvanPombo** [inductiva/inductiva#612]
# Goal and Reasons
The goal of this issue is to discuss the implementation of a module for the manipulation and pre-processing of CAD Objects - Computer Aided Design -  into Inductiva package.  

The first version of this module will focus on loading and manipulation of the objects. Thereafter, we can decide if we pass these objects to the simulators or if we keep passing the file path. Moreover, in the future this can connect more easily with the pre-processing meshing tools and/or parameterisation features.

Why is this useful for the API? To explain let me restrict the WindTunnel scenario (Structural mechanics may also use this, as well as FluidTank/FluidBlock, HeatSink, etc...). We initialise the WindTunnel by defining the geometry of the domain as:
```python
import inductiva

scenario = inductiva.fluids.WindTunnel(domain={"x": [-5, 10], "y": [-5, 5], "z": [0, 8]})
```

This means that the WindTunnel will have 15x10x8 (x,y,z) m x m x m dimensions - and notice that air flows from -x to x axis. When engineers develop their CAD models, the dimensions, orientation and position of the model may not fit the physical representation of the WindTunnel - in particular in Reynolds models. Online there are various examples where the objects are set in different axis of reference (rotated), and their initial position are distant from the origin (0,0,0). In turn, this affects the simplicity to use the WindTunnel since at least they will have to know the dimensions and position of their object before defining the domain.

Furthermore, for some objects like an airplane wing users may want to rotate it to consider different angles of attack.

To finish, another goal for this CAD Object is the ability to also clean the files and prepare different formats to be fed into our simulators. We clean the file first as we want to feed it to the scenario, instead of tweaking all simulators to consider all types of file formats possible.

## Naming: CAD Model?

The first consideration is the name, I believe CAD Object or CAD Model are the most appropriate names, with inclination to CAD Model since it is what appears the most online. Initialisation will always be done from files, since they main goal for now is to manage outside CAD models.

```python
# Initialise
object = inductiva.geometry.CADModel("vehicle.obj")

# Print info about the object mesh.
object.info()
```

From here on, we work with the mesh structure.

## Manipulation

The three main manipulation tools are: translation, rotation, resize.

```python
# Translate the object with a vector (list) in place
object.translate([10.,-5,3], inplace = True)

# Rotate the object by scalar values in [0, 360] and in a certain direction (not inplace)
object = object.rotate("x", 90)
object = object.rotate("y", 90)

# Scale all of the object by a scalar value or rescale in three different directions with a list (all inplace)
object.scale(0.5, inplace = True) # Decrease the object size by half
object.scale([1., 0.5, 2.], inplace = True) # Maintain in the x-axis, reduce on the y and duplicate on the z
```

Note that rotations are not commutative, i.e., rotating first in the x-direction by 90, then in the y-direction by 90, is different 
than doing first in the y-direction and then the x-direction with 90. Thus, rotate needs to be separately done for each variable.

## Plotting

To visualise all your transformations you are one plot away with:

```python
# Render interactive plot to rotate the camera easily
object.render()
```

There may be tools in the future to add materials, but let's keep it as raw as possible, with a few coloring arguments.

## Final Remarks

The implementation will use `meshio, pyvista` library and will focus first on two file formats - STL and OBJ. First, we implement these features and test them throughly for these formats. Thereafter, we can move to other file formats. The key aspect is that one library might not be enough to handle all formats.

This is the first iteration on the design of `CADModel` object, and all the feedback is much appreciated!

**Comment by IvanPombo** [comment]
Asking for feedback on this issue and possible extra feature requests (for example for the structures module) to start implementing this in the next few days.

**Comment by hpenedones** [comment]
Thanks Ivan, what you described seems reasonable (I prefer object rather than model, because in the Machine Learning community we use model for ML models, but I understand that mechanical engineering community might use model for the CAD object).

My main concern is that this would require a couple more library dependencies on the client, right?

**Comment by IvanPombo** [comment]
Yes, you are right. In principle it will just be `pyvista`. However, it is a trade-off necessary if we want to keep users able to do everything in the API. This will be a feature for advanced users, so they could install the extra for it.

**Comment by sarmento** [comment]
For me, the most important thing has to do with how we/the users do meshing. Meshing is very important and it will have impact on the cost of the simulation, but also on its stability. 
There are multiple algos for meshing. 
Which ones are we planning to use?
Will meshing occur on the client or on the server side?

On the viz side: do we have interactive viz or just static renders?

**Comment by IvanPombo** [comment]
I agree, and that is why I am not contemplating that part here yet. This is a first step on that direction, and after, I can more easily play with those things! 
The problem with meshing is that it depends of the application - meshing methids for finite volume methods and finite element methods are different. For example, gmsh is specifically for finite element. Then, openfoam has a tool to generate a finite volume mesh for running. 

There are all of things here, that I just want to start thinking after this step. However, for real applications I can already state that meshing needs to occur on the server.

The visualizations are interactive with pyvista if we do them on the client (or with a web interface).

Thank you for the feedback!

**Comment by fabiocruz** [comment]
Hi @IvanPombo. I think we may be using the terms "CAD model" and "mesh" almost interchangeably, but they are not in fact the same. See [this](https://3space.com/mesh-vs-cad) or [this](https://www.ddd-imension.com/en/post/what-is-the-difference-between-mesh-models-and-parametric-3d-models) for a reference.

I think the capabilities you are describing here assume you always start with a mesh described in a file, so I think we should name this new class as `Mesh`.

**Comment by fabiocruz** [comment]
Regarding the class methods:
- I don't see why we need the `inplace` parameter. Can we drop it?
- The `rotate` method should allow the first argument to be an iterable defining the axis of rotation, in case we want to rotate a mesh around an axis other than x, y or z.
- Are you planning to have the `scale` method scale the mesh dimensions relative to its center or corner? For instance if I scale a 1 x 1 x 1 cube mesh with its lower corner at (1, 1, 1) by a factor of 3, do I get a 3 x 3 x 3 cube with the lower corner at (1, 1, 1) or with its center at (1.5, 1.5, 1.5)?

**Comment by IvanPombo** [comment]
> this

I think all of the features above are useful for both types of models. Moreover, even though we have a mesh coming from an .STL or .OBJ file, this won't be necessary the meshes used in the simulation, so I wanted to separate both things here as well. Moreover, in the future we want to establish some parameterisation on these objects, that is why I was thinking more about CAD than mesh. But I agree, that `CADModel` may not be the best name in general...

To answer the rest:
- I feel the `inplace` method is good to avoid `object = object.rotate(...)`. To be honest, I don't see a reason to drop it, since it provides extra capabilities to the user and he can use as he desires.
- Seems good!! 
- I will iterate on this aspect and try to understand the best approach - maybe try to provide both options. 

Thanks for this advice!
