### ISSUE TITLE
[ProteinSolvation] Render interactive doesn't work on Google Colab

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#614]
Videos depicting the protein trajectory fail to play within Google Colab. While it's possible to render a single image, the video playback is not working. This problem is likely attributted to an [issue](https://github.com/openmm/openmm_workshop_july2023/issues/11) associated with NGLview and the specific version of ipywidgets in use.

**Comment by hpenedones** [comment]
So what are the circumstances where the interactive visualisation works? With local Jupyter notebooks?

**Comment by cristianacarpinteiro** [comment]
> So what are the circumstances where the interactive visualisation works? With local Jupyter notebooks?

Yes, in normal jupyter notebooks! But I will try to fix it for google colab too.

**Comment by IvanPombo** [comment]
This is still an issue, but the direction we are going this will be eventually removed, so that visuals are done in the backend.
