### ISSUE TITLE
[Documentation]: Opening external links in other tabs

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#618]
Hi team:

I was checking the docs on our github, and I would like to bring an idea that has to do with an UX aspect regarding how users go through documentation. 

Ideally, links to external resources should open in a different tab, so that the reader does not lose sight of our docs. 
However, it seems that opening links in different tabs is not so trivial in github readmes, but there seems to be a solution:

https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

Please consider this solution.

Thank you!

**Comment by luispcunha** [comment]
I don't think there's a proposed solution there (the accepted answer says it is not possible to do it) or am I missing something?
