### ISSUE TITLE
[Coastal Area]: confusing color maps on bathymetry and video rendering.

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#632]
When I render a random bathymetry I get this:

![base_bathymetry](https://github.com/inductiva/inductiva/assets/1358685/4e184f8f-39d9-4916-9af8-5b659571903b)

This is a depth map, so in this case, deep is positive and gets rendered to yellow and above zero i.e. out of  is negative and get's rendered to blue. 

However, the corresponding video will then show wave height. 

https://github.com/inductiva/inductiva/assets/1358685/1d2a3f9d-33ad-4120-9140-7893181604cf

So, out of water now becomes yellow. This is very confusing.

We can either:

a) change the colormaps such as the same things (below/above water level) have the same colors, or
b) use a different colormap for the bathymetries such that there is no direct connection (e.g. browns/greys).

As it is, this is extremely confusing.

**Comment by IvanPombo** [comment]
I agree completely, thanks for spotting this @sarmento! Can you focus on this @david451lima?

**Comment by david451lima** [comment]
Fixed with #647

**Comment by IvanPombo** [comment]
> Fixed with #647

Could you had the vizs? :)
