### ISSUE TITLE
Missing param?

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#669]
Apparently, this:
```
input_dir = inductiva.utils.files.download_from_url(
    "https://storage.googleapis.com/inductiva-api-demo-files/"
    "dualsph-flow-cylinder.zip"
)
```

will result in unzipping the file, and (creating a directory).
I think it would be better to:

1) have a parameter called decompress=True to explicitly force decompression
2) the file should be named in a way that suggests that this is a directory: "dualsph-flow-cylinder_directory.zip"

This is not urgent.

**Comment by IvanPombo** [comment]
This was solved with the latest change in this function. I will rename the files that are currently in the api-demo bucket to include the directory name.
