### ISSUE TITLE
[Docs] More user friendly title and formulation

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#676]
Here:

https://github.com/inductiva/inductiva#async-api

we have a title that is not clear for the outside users: "Async API". We need to transform this is something that makes immediately sense from the point of view of a user.

For example, 

* "Running multiple simulations in parallel"
* "Launching simulations in background"

Try to rewrite this text from the point of view of user and less from the point of view of the technical details (that can come later): what is it that the user can (additionally) do?

**Comment by IvanPombo** [comment]
I have addressed this in the PR #679, but for the next release this will drop, since we all simulations will be async.
