### ISSUE TITLE
[Scenarios] Default output files definition missing in several scenarios

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#681]
At the moment, there are several scenarios that don't have the default download files.
<img width="752" alt="image" src="https://github.com/inductiva/inductiva/assets/114397668/65efcb8e-8e16-4c0e-91bb-3c4409714d44">

**Comment by IvanPombo** [comment]
This is a non-issue currently, since most scenarios don't require specific default files. Since our paradigm is to eventually do everything from storage, this file will also go away.
