### ISSUE TITLE
[Documentation] Optimal GitHub links

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#686]
There are many non-optimal links in the documentation that point to the "top" of the github page, instead of the point where the user can start reading the follow up information.

For example, if the user click on a link with this URL (top of the github page)

https://github.com/inductiva/inductiva/tree/main/inductiva/molecules/protein_solvation

it get presented a list of python files and directories, but if that link had this URL (readme section):

https://github.com/inductiva/inductiva/tree/main/inductiva/molecules/protein_solvation#readme

then the user would immediately see text, which is a much better user experience.
This looks like it is just a detail, but I think we need to fix this for this release because it has huge impact in the experience.

**Comment by sarmento** [comment]
@IvanPombo : check my previous comment.

**Comment by cristianacarpinteiro** [comment]
I tested it and it was working. But it appears that it only works if you open it in a new tab. I will try that way now.

**Comment by sarmento** [comment]
Which browser are you using?
If I open on a different tab I still don't get the effect I was hoping for.

**Comment by sarmento** [comment]
@luispcunha : there are some documents you wrote that could also have optimal links.
E.g. 

https://github.com/inductiva/inductiva/tree/main/inductiva/tasks#tasks

**Comment by cristianacarpinteiro** [comment]
> Which browser are you using? If I open on a different tab I still don't get the effect I was hoping for.

I am using google chrome.

**Comment by cristianacarpinteiro** [comment]
Ok, with the links pointing to the title is working on my Google chrome, even if I dont open in a new tab.
