### ISSUE TITLE
[Documentation] Missing README file 

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#687]
We need a short readme file where we present on paragraph for each of the tutorials here:

https://github.com/inductiva/inductiva/tree/main/demos/tutorials

(and we should point to that readme from the main page)

"And you are good to go! You can start [exploring our tutorial notebooks](https://github.com/inductiva/inductiva/tree/main/demos)."

**Comment by IvanPombo** [comment]
On it! But to be honest I don't feel confident about any of these tutorials since they can be outdated. We can split tasks and fix them, while adding that line in the readme.

**Comment by sarmento** [comment]
If we are not confident, then we should not point to them from the 1st page :)
Leave them there but remove the link.
Please open an issue for reviewing the notebooks and then, when we have all reviewed then we can point back to them again.
