### ISSUE TITLE
[Info to the user] Add more detail (and a few more little things)

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#697]
Here is a dump of running on example from the terminal (swash)

```
INFO:absl:Task ID: 1695390640821818395
INFO:absl:Creating input archive...
INFO:absl:Input archive created.
INFO:absl:Input archive size: 1.56 MiB
INFO:absl:Uploading input...
INFO:absl:Input archive uploaded.
INFO:absl:Task request submitted.
INFO:absl:Waiting for resources...
INFO:absl:The task is being executed remotely.
INFO:absl:Task completed successfully.
INFO:absl:Task completed successfully.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 76.5M/76.5M [03:20<00:00, 400kiB/s]
INFO:absl:Post-processing tools are available through the output object.
INFO:absl:Starting to render video from simulation data...
INFO:absl:Writing mp4 file to movie.mp4.
```

Here are my comments/wishes:

```
INFO:absl:Task ID: 1695390640821818395
```

1) I wish I had a timestamp/date in all these messages.
2) I wish I had a link so I could be redirected to the console

```
INFO:absl:Creating input archive...
```
I wish I had more context: "Creating input archive to be upload to inductiva.ai"
```
INFO:absl:Input archive created.
INFO:absl:Input archive size: 1.56 MiB
```
These to messages could be merged.
Also, what is "MiB"? :)

```
INFO:absl:Uploading input...
```
"input archive."
Since we have a progress bar for downloading, can we have one for uploading.
```
INFO:absl:Input archive uploaded.
INFO:absl:Task request submitted.
```
to which pool?
```
INFO:absl:Waiting for resources...
```
If you could tell me a bit more, that would be great.
Metric suggestion (for our metrics): how long is it taking from a task to be picked up?
If we have live access to that metric, then let's show it here ("Current average waiting time = Xs").

```
INFO:absl:The task is being executed remotely.
```
Can you tell me which hardware picked this up?
```
INFO:absl:Task completed successfully.
INFO:absl:Task completed successfully.
```

Why are repeating this message?
```
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 76.5M/76.5M [03:20<00:00, 400kiB/s]
```
What does this progress bar refer to? (I know it's download but it's not explicit)
Also, print the path to where this data is being downloaded

```
INFO:absl:Post-processing tools are available through the output object.
```
No idea why you are telling me this. This message is confusing. You could tell me that they are NOT available so I would have to pip install something, but this message seems unnecessary.

```
INFO:absl:Starting to render video from simulation data...
```

Why not tell me more? How many frames are there? What FPS did we choose?

```
INFO:absl:Writing mp4 file to movie.mp4.
```

But which directory?

These are not a priority but please try to understand these point more about how we need to think about how we inform the user. Eg.

* are we being consistent in the terms / strategy? 
* are we giving information that allows the user to learn or correct potential mistakes (e.g. wrong queue)?
* are we preparing the user for what comes next?

**Comment by sergiomsantos** [comment]
See also https://github.com/inductiva/tasks/issues/26
