### ISSUE TITLE
Remove n_cores argument from OpenFOAM 

### ISSUE THREAD

**Issue by IvanPombo** [inductiva/inductiva#700]
With the need to remove the `n_cores` dependency from the Client, this issue opens the discussion for the ways to approach it for the OpenFOAM simulator and the corresponding scenarios. Below, I highlight what were the main problems with them and the possible fixes. Moreover, notice that these things are also related with the low-level simulator. So the approach to solve them needs to consider this generality.

The first thing is concerned with the commands passed:
`{"cmd": "mpirun --allow-run-as-root -np {{ n_cores }} snappyHexMesh -overwrite -parallel", "prompts": []}`

Breakdown: 
- the flag `--allow-run-as-root` should be added in the backend when seeing the "mpirun" command, or the docker should not be running as a root (this idea also fixes the use of OpenFOAM as a simulator).
- the number of cores can be avoided here (i.e., remove "-np {{ n_cores }}", and the executer will use all cores available;

Hence, the command a user would be expected to pass is `{"cmd": "mpirun snappyHexMesh -overwrite -parallel", "prompts": []}`.

The second thing is that the number of cores needs to be changed on the `decomposeParDict` template file. This file breaks the domain into pieces equal to the number of processors used. However, we only know the number of cores  of the machine to be used in the simulation inside the executer in the backend. 

Solution possibilities:
- Either, create a jinja style flag - `$n_cores` - that will be changed inside the OpenFOAM executer on the backend. Notice that this is also required for the low-level simulations.
- Move the commands of the scenarios to the backend. This fixes the specific case of the scenarios (even the first point). But forgets about the low-level simulators.

**Comment by cristianacarpinteiro** [comment]
I think it's better to keep the command files on the client side. This way, users can openly access the code behind the scenario, which can serve as "inspiration" for them to create their own scenarios.

**Comment by IvanPombo** [comment]
I forgot to mention that the commands for OpenFOAM look like this:
```
[
    {"cmd": "surfaceFeatures", "prompts": []},
    {"cmd": "blockMesh", "prompts":[]},
    {% if n_cores > 1 %} 
    {"cmd": "decomposePar -copyZero", "prompts":[]},
    {"cmd": "mpirun --allow-run-as-root -np {{ n_cores }} snappyHexMesh -overwrite -parallel", "prompts":[]},
    {"cmd": "reconstructParMesh -constant", "prompts":[]},
    {% else %} 
    {"cmd": "snappyHexMesh -overwrite", "prompts":[]},
    {% endif %}
    {"cmd": "potentialFoam", "prompts":[]},
    {% if n_cores > 1 %} 
    {"cmd": "mpirun --allow-run-as-root -np {{ n_cores }} simpleFoam -parallel", "prompts":[]},
    {"cmd": "reconstructPar -latestTime", "prompts":[]}
    {% else %} {"cmd": "simpleFoam", "prompts":[]}
    {% endif %}
]
`
``

which are altered based on the number of cores for the simulation. That was part of the reason I wanted to send them to the backend... However, I believe they can be turned around and I will check how to approach this further.
