### ISSUE TITLE
User experience for Autoscaling of instance groups

### ISSUE THREAD

**Issue by begaiym-k** [inductiva/inductiva#701]
I am working on adding the autoscaling feature to the Machine Group and I am trying to decide on the user experience. 

In the Google Cloud Python API you can set the autoscaling only after the instance group is created, and when setting it you pass the number of maximum and minimum instances and the CPU utilisation target (a new instance will be launched when this target is hit).

So there are two ways to do it: 

1) First one is to give the users full control over these parameters, but in that case the code sequence gets a little complicated since they will have to do it after they start the machine group and it will override the initial number of machines, the example code of how it will look like is shown below.
```python
mg = inductiva.reaources.MachineGroup(num_machines=1)
mg.start()
mg.enable_autoscaling(max_machines=4, min_machines=1, cpu_utilization=0.4)
```

2) Or, we can take all the decision making into the backend, and simplify it for the user, but then most of these parameters will be set by us, and the maximum number of machines is the number set initially. 
```python
mg = inductiva.reaources.MachineGroup(num_machines=5, autoscaling=True)
mg.start()
```

Which one should I go for?

**Comment by IvanPombo** [comment]
As is, the second option seems the most appropriate. 

The purpose of autoscaling is to just provide the flexibility of starting machines on demand - when simulations arrive - and allow to save slightly on the costs. In my opinion, the option 2 provides this interface cleanly!

Obviously, we are not giving all the power to the user with the option 2. With the approach you present, there are few things that concern me on option 1, like the `cpu_utilization`, which isn't clear to us at the moment. For example, if we launch a machine with 2 physical cores and a ratio of 1vCPU per physical core, Google Cloud still counts usability as 50% usability for using the 2 physical cores - so the interface to the user is way more trickier at this moment in time. 

Moreover, I don't really like the overriding of the initial `num_machines`, so I would say the `max_machines=num_machines` always. Thinking further, it seems that doing `mg.start()` for 4 machines would launch those machines first, and then the autoscaling would need to kill these machines to reduce to the `min_machines` number. This is cumbersome in terms of time and usage. To avoid it, you could pass these commands immediately on the start, together with the `autoscaling` argument.

So I would say, the first option should be something like:
```python
mg = inductiva.resources.MachineGroup(num_machines=4)
mg.start(autoscaling=True, min_machines=1, cpu_utilization=0.5)
```

What do you guys think?

**Comment by hpenedones** [comment]
I'm not sure on this one, but if the parameters we want to expose are really significantly different, another option is to have a separate class name:

```python
mg = inductiva.resources.ElasticMachineGroup(
                     min_machines=1,
                     max_machines=4, 
                     cpu_utilization_threshold=0.5)
mg.start()
```

Something like that... or `AutoscalingMachineGroup` (which is a bit longer name...)

**Comment by begaiym-k** [comment]
> I'm not sure on this one, but if the parameters we want to expose are really significantly different, another option is to have a separate class name:
> 
> ```python
> mg = inductiva.resources.ElasticMachineGroup(
>                      min_machines=1,
>                      max_machines=4, 
>                      cpu_utilization_threshold=0.5)
> mg.start()
> ```
> 
> Something like that... or `AutoscalingMachineGroup` (which is a bit longer name...)

That's a good idea if we want to give more control to the user. However, as Ivan said at the moment CPU utilisation is not actually working because of the virtual and physical core differences. (Simulations use physical cores which is half of the total vCPU cores in the machine, and CPU utilisation only looks at the vCPU usage). So I don't think that this parameter is ready to be exposed, my bad for putting it out there in the first place. So as a first step maybe we can just implement a simpler solution with `autoscaler=True` and see the feedback we receive, and then decide if we should create a new class in the client side. Because no matter the client interface, the backend will be more or less the same. Wdyt?

**Comment by sarmento** [comment]
I am not sure about what @begaiym-k said. Cores are cores, virtual or real. Then, there is threads. Some cores allow for two threads to run concurrently (e.g. AMD) while others don't (Intel). If I get it correctly -- not sure -- vCPU are actually equivalent to threads. That's way on Xeon CPUs we have a direct mapping from cores to vCPUs and on AMD we have a mapping from cores = 2 theads = 2 vCPUs. 
Can anybody check this?

I think we should only think in terms of (v)CPUs, and maybe that is the parameter we should have exposed.

Having said that, I am not sure if that is a problem for autoscaling, right.
This seems good:
```
mg = inductiva.resources.ElasticMachineGroup(
                     min_machines=1,
                     max_machines=4, 
                     cpu_utilization_threshold=0.5)
mg.start()
```
But what is missing here is the machine type.

**Comment by hpenedones** [comment]
I think there are a couple of orthogonal choices here:

1) whether we give control to the user about the autoscaling rule (e.g. expose an argument for that, or we just decide what's best, like we do for the default pool -- and the user does not pick that)
2) whether we create a separate class name for elastic machine groups, or we keep just one "MachineGroup" class with some additional arguments.

In my opinion it is fair enough to:
1) not expose the scaling criteria regarding cpu usage, and we pick a good one
2) if the class constructor of the two potential classes can be natural unified, I also don't oppose to having a single class. For example:


```python
mg = inductiva.resources.MachineGroup(num_machines=5, autoscaling=True)
mg.start()
```

and document the `autoscaling` argument with something like "if set to True the size of the Machine Group will vary between 1 and num_machines depending on the computational load of machines. If set to False, it will have a fixed size = num_machines" ? Potentially documenting the actual details regarding CPU usage thresholds that we use from Google cloud...

The things I would definitely avoid are:
-  adding extra arguments to `start` method 
-  adding a new method like `enable_autoscaling`

**Comment by sarmento** [comment]
```
whether we create a separate class name for elastic machine groups, or we keep just one "MachineGroup" class with some additional arguments.
```

I prefer this. I think it makes the semantics cleaner. For example, why do we think the good starting point for an elastic group is 1 machine? It can be, for example, 5 and we are ok increasing it to 100. So, I really think there are two parameters to set the bounds and we can't assume that the min param is 1.

**Comment by hpenedones** [comment]
Ok, so I guess we need a new class. I think it's fair enough and we continue with the policy of making choices quite explicit.

**Comment by IvanPombo** [comment]
> I am not sure about what @begaiym-k said. Cores are cores, virtual or real. Then, there is threads. Some cores allow for two threads to run concurrently (e.g. AMD) while others don't (Intel). If I get it correctly -- not sure -- vCPU are actually equivalent to threads. That's way on Xeon CPUs we have a direct mapping from cores to vCPUs and on AMD we have a mapping from cores = 2 theads = 2 vCPUs. 
> 
> Can anybody check this?
> 
> 
> 
> I think we should only think in terms of (v)CPUs, and maybe that is the parameter we should have exposed.
> 
> 
> 
> Having said that, I am not sure if that is a problem for autoscaling, right.
> 
> This seems good:
> 
> ```
> 
> mg = inductiva.resources.ElasticMachineGroup(
> 
>                      min_machines=1,
> 
>                      max_machines=4, 
> 
>                      cpu_utilization_threshold=0.5)
> 
> mg.start()
> 
> ```
> 
> But what is missing here is the machine type.
> 
> 
> 
> 
> 
> 
> 
> 

I think this is a parallel issue, that we should address and clarify since it also interferes with the simulators. But we have been feeling the pain from the vCPU with the default machines, so @begaiym-k reason is still a fair point here. 

@sarmento I will address you tomorrow with a complete clarification on the cores. 

@hpenedones Thanks for the clarity! The simple approach seems the best to start and serve the purpose, and if users ask for more we give them more :)

**Comment by IvanPombo** [comment]
> ```
> 
> whether we create a separate class name for elastic machine groups, or we keep just one "MachineGroup" class with some additional arguments.
> 
> ```
> 
> 
> 
> I prefer this. I think it makes the semantics cleaner. For example, why do we think the good starting point for an elastic group is 1 machine? It can be, for example, 5 and we are ok increasing it to 100. So, I really think there are two parameters to set the bounds and we can't assume that the min param is 1.
> 
> 

But I can also pose the reverse question: isn't the good end point for an elastic group to be 1 machine? Achieve the minimal cost as simulations finish... I believe this was the main reason to have the autoscaling implemented. 

I understand the point of giving total control, but that also brings more complexity to the interface, learning curve and user decision making.

**Comment by sarmento** [comment]
I don't think it brings more complexity because the name of the class become unambiguous. I think complexity arises from having classes that can have multiple behaviors and thus require parameters to set a conditional behavior. 

Having these multiple possible behaviors also makes wrting the class more complicated. In many cases you will have to have a "if is_elastic" condition inside some functions. Think for example about the cost estimate function. If it is not elastic it is easy. If it is elastic you are probably going to do some estimate or show different conditions. We certainly don't what to have class methods that have to check a number of parameters given by the user to then decide what to do. Having two separate classes makes not only the interface cleaner for the users but it also allows our own coding fo be simpler. They are both important aspects.

**Comment by begaiym-k** [comment]
Thanks everyone for sharing different perspectives of this issue. To summon it, I think the right direction for now will be to have a separate class and make it explicit for the user, this is good in case we want to expose more parameters for the users. @sarmento brought a very fair point of estimating the prices of elastic machine groups, and I am not sure how exactly we will do it for now (probably with a new database, that's on its way, it will be easier).
