### ISSUE TITLE
[Feature] Let users decide where to store task outputs

### ISSUE THREAD

**Issue by cristianacarpinteiro** [inductiva/inductiva#748]
In yesterday's meeting, we made the decision to delay the implementation of #704 and instead prioritize the development of a feature that empowers users to select the storage location for their simulation outputs. This decision will enable us to better the organization of users' storage buckets and provide them with a more intuitive way to manage their data.

For the user interface interaction with the client, I propose the following code snippet:

```python
scenario = inductiva.molecules.ProteinSolvation(
     protein_pdb=insulin_pdb_file,
     temperature=300)
task = scenario.simulate(simulation_time_ns=0.01, 
                        storage_directory="protein_id/temp_30")
print(task.storage_path)

inductiva.storage.rmdir(task.storage_path)
```

With this code, a directory will be created within the user's storage, and the simulation outputs will be stored in a folder structured as follows: `protein_id/temp_30/task_id`. We've decided to keep the `task_id` unchanged for now. In the future, we can explore alternative approaches to make the task ID more descriptive.

As for the variable naming for `storage_directory`, I have a few more suggestions:

1. `parent_folder`

2. `save_path`

3. `experiment_name`

4. `bucket_directory`

Which one do you prefer?

**Comment by IvanPombo** [comment]
I think to be agnostic for all future storage possibilities, I like the `storage_dir` option. However, what I notice on the code snippet is the difference between how to know this with the task. I would prefer having as a single name.
