### ISSUE TITLE
Deprecate inductiva.api_key = "YOUR_API_KEY"

### ISSUE THREAD

**Issue by sarmento** [inductiva/inductiva#800]
As we streamline our key management process, we really want to avoid having users define keys directly in their code. 

Let's start by removing all references to 

```
inductiva.api_key = "YOUR_API_KEY"
```

in our documentation.
Some examples:

* https://github.com/inductiva/inductiva#windtunnel-example
* https://github.com/inductiva/inductiva#example
* https://github.com/inductiva/inductiva/tree/main/inductiva/molecules/protein_solvation#example
* https://github.com/inductiva/inductiva/tree/main/inductiva/coastal#example-1-simulating-waves-on-a-synthetic-bathymetry
* https://github.com/inductiva/inductiva/tree/main/inductiva/fluids/fluid_tank#example
* https://github.com/inductiva/inductiva/tree/main/inductiva/fluids/wind_tunnel#example

Also, change:

* https://github.com/inductiva/inductiva#api-access-tokens

To: 

Obtain your API token using Inductiva Console https://console.inductiva.ai/ and follow the instruction for setting up the key and testing your access.
Once you the key is correctly installed you are good to go! 
You can start exploring Inductiva API with the examples below.

@hpenedones : can we get a direct link to the console page where we generate the key?

**Comment by AugustoPeres** [comment]
Closing as this was handled in https://github.com/inductiva/inductiva/pull/1018.
No references to `inductiva.api_key = ""` exist in the docs
