### ISSUE TITLE
MDBC

### ISSUE THREAD

**Issue by LL650** [inductiva/inductiva#881]
No valid normal vectors for using mDBC

**Comment by IvanPombo** [comment]
Hi @LL650! Could you elaborate a bit more on your error? Do you have any logs you can show us?

**Comment by LL650** [comment]
Hello, I am using DualSPHysics5.2 and want to use MDBC in Chrono case Pelamis, so I added the option of MDBC in the corresponding XML file, but the following error that no valid normal vectors for using MDBC occurs when executing. I'd like to ask for your help.
![error](https://github.com/inductiva/inductiva/assets/152636486/17e23c8d-eb59-4cf7-bbca-62711d35d103)

**Comment by IvanPombo** [comment]
> Hello, I am using DualSPHysics5.2 and want to use MDBC in Chrono case Pelamis, so I added the option of MDBC in the corresponding XML file, but the following error that no valid normal vectors for using MDBC occurs when executing. I'd like to ask for your help. ![error](https://private-user-images.githubusercontent.com/152636486/287772897-17e23c8d-eb59-4cf7-bbca-62711d35d103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTAyNDEsIm5iZiI6MTcwMTcwOTk0MSwicGF0aCI6Ii8xNTI2MzY0ODYvMjg3NzcyODk3LTE3ZTIzYzhkLWViNTktNGNmNy1iYmNhLTYyNzExZDM1ZDEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNzEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2VkNTIxYTJkY2NiMmZhNGNjYTVkNGRiZDRjNWM2NDFiOGZmNGEwYzY4Y2E1YmRlMzhmOWE3NTQ0YjFlYThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jncu1pSCOk-ekyZublMJmWc4LC-07eHTW_sPQ1Khs8s)

For more specific questions on DualSPHysics you should address them at: https://github.com/DualSPHysics/DualSPHysics.
This repository provides an interface to call DualSPHysics and other simulators.
