### ISSUE TITLE
Excessive debug logging after "import inductiva"

### ISSUE THREAD

**Issue by fdrocha** [inductiva/inductiva#929]
I have been having an issue where after I import inductiva module I get a bunch of unwanted debug messages coming from *other* libraries. E.g., if I `import inductiva` inside an ipython terminal, I get messages like

`2024-01-10 19:40:34 DEBUG Using selector: KqueueSelector`

after each time I press enter. And if I try to plot anything with matplotlib I get spammed with debug messages about fonts. This is particularly bad for some of the code examples. E.g., the render step for FluidTank produces *many* pages of debug statements.

Having had a quick look at the code, I believe the issue is coming from

https://github.com/inductiva/inductiva/blob/800238015024980768e76a558e9437c43183c8fd/inductiva/__init__.py#L30-L32

which sets the logging flags for all libraries, not just inductiva. If I remove those lines, issue is fixed.

There must be a way of keeping changing the logging level just for inductiva library, but I am not sure what it is. I think it probably would be better to switch to that.

@IvanPombo @hpenedones

**Comment by IvanPombo** [comment]
@fdrocha the fix should be already available on the main package, could you try again?

**Comment by fdrocha** [comment]
Thanks @IvanPombo! Looks good now
