### ISSUE TITLE
Removing sidebar and footer MD files?

### ISSUE THREAD

**Issue by hpenedones** [inductiva/inductiva#968]
In principle, we will be using readthedocs, to build and host the documentation of the API (at least for now).
See current version here for the development branch here:
https://inductiva-research-labs-inductiva.readthedocs-hosted.com/en/development/index.html
Readthedocs is setup to use sphinx to build the docs:
https://github.com/inductiva/inductiva/blob/main/docs/conf.py

and the index.md file defines the structure of the side bar:
https://github.com/inductiva/inductiva/blob/development/docs/index.md

Therefore I believe that the following files could now be safely deleted (correct @IvanPombo @sergiomsantos)?
https://github.com/inductiva/inductiva/blob/development/docs/_Sidebar.md
https://github.com/inductiva/inductiva/blob/development/docs/_Footer.md

**Comment by sergiomsantos** [comment]
Those files were just the result of copying the wiki files ipsis verbis. They can be deleted as long as the navigation across documents keeps working.
@IvanPombo please check this is the case.

**Comment by IvanPombo** [comment]
This was closed with the recent push to v0.4.1
